# Generated by Django 2.1.15 on 2021-11-21 10:45

import article_app.models
from django.db import migrations, models
import utils.validation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hero', models.ImageField(blank=True, max_length=1500000, null=True, upload_to=article_app.models.explantion_images, validators=[utils.validation.validate_image], verbose_name='Hero Image')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
