export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const GET_USER_INFO = "GET_USER_INFO";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_ERROR = "GET_USER_INFO_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_PROFILE = "CLEAR_PROFILE";

export const GET_ARTICLE = "GET_ARTICLE";
export const GET_ARTICLES = "GET_ARTICLES";
export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";

export const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS";
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
export const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS";
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";


export const GET_ARTICLE_ERROR = "GET_ARTICLE_ERROR";
export const GET_ARTICLES_ERROR = "GET_ARTICLES_ERROR";
export const CREATE_ARTICLE_ERROR = "CREATE_ARTICLE_ERROR";
export const UPDATE_ARTICLE_ERROR = "UPDATE_ARTICLE_ERROR";
export const DELETE_ARTICLE_ERROR = "DELETE_ARTICLE_ERROR";